services:
  api_gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - article_service
      - comment_service
      - ai_service
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - blog_network
    labels:
      - "com.consul.service.name=api_gateway"
      - "com.consul.service.port=8000"

  user_service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DB_URL=mysql+aiomysql://root:root@host.docker.internal:3306/analysis_blog_db
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - blog_network
    labels:
      - "com.consul.service.name=user_service"
      - "com.consul.service.port=8001"

  article_service:
    build:
      context: .
      dockerfile: ./services/article-service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DB_URL=mysql+aiomysql://root:root@host.docker.internal:3306/analysis_blog_db
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - blog_network
    labels:
      - "com.consul.service.name=article_service"
      - "com.consul.service.port=8002"
  comment_service:
    build:
      context: .
      dockerfile: ./services/comment-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DB_URL=mysql+aiomysql://root:root@host.docker.internal:3306/analysis_blog_db
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - blog_network
    labels:
      - "com.consul.service.name=comment_service"
      - "com.consul.service.port=8003"

  ai_service:
    build:
      context: .
      dockerfile: ./services/ai-service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DB_URL=mysql+aiomysql://root:root@host.docker.internal:3306/analysis_blog_db
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - blog_network
    labels:
      - "com.consul.service.name=ai_service"
      - "com.consul.service.port=8004"
  consul:
    image: consul:1.14.5
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge